/*******************************************************************************
*
* Create 5 processes from a common parent and ensure that the parent terminates 
* after cleaning all the terminated children using waitpid(). The waitpid() must 
* be called after all the children are created and the parent has completed its 
* work real work,if any; in addition, you must compile 5 different program files 
* to in children processes to generate their respective object files ; the parent 
* process must use waitpid() to collect the termination status of children processes 
* – based on the exit code information generated by children processes, link all 
* the object files to generate the final, linked program/application. In addition, 
* the generated binary executable must be loaded in a new process, if the linking 
* is successful
*
*******************************************************************************/

#include "4.h"
int main(int argc, char **argv) 
{
	pid_t pid;
	int loop;

	/* char array to store the string commands to execute the files */

	char *prog_list[][5] = { {"cc", "-c", "./exec1.c", NULL},
				 {"cc", "-c", "./exec2.c", NULL},
				 {"cc", "-c", "./exec3.c", NULL},
				 {"cc", "-c", "./exec4.c", NULL},
				 {"cc", "-c", "./exec5.c", NULL} };

	for (loop = 0; loop < 5; loop++)
	{
		/* fork the process to create object file in child process */
		pid = fork();
		/* give the error statement for abnormal fork(); */
  		
		if (pid == -1)
    		perror("fork failed");

		/* allow only child processes to create object files */
  		if (pid == 0) 
  		{
    			execv( "/usr/bin/cc", prog_list[loop] );
			waitpid( pid, 0, 0 ); // termiate process once object file is created
  		}
  		else 
  		{
    			waitpid( pid, 0, 0 ); // terminate other procesess created with fork()
  		}
	}

	/* now user another array to create executable file */
	char *exec_file[] = {"cc", "exec1.o", "exec2.o", "exec3.o", "exec4.o", "exec5.o", "-o", "calculations", NULL};

	/* load the files in child process */
	pid = fork();

	if(pid == 0)
	{
		execv("/usr/bin/cc", exec_file);
		waitpid(pid, 0 , 0); // termiate process once executable file is created
	}

	execl("./calculations", "calculations", NULL); // execute the file in parent process
	waitpid(pid, 0 , 0 ); 
	
  	waitpid(pid, 0, 0);
	return 0;
}
